language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- wget -O ./_data/news.csv $(bundle exec yaml get news-feed -F=_config.yml)
- wget -O ./_data/events.csv $(bundle exec yaml get events-feed -F=_config.yml)
- wget -O ./_data/profiles.csv $(bundle exec yaml get faculty-feed -F=_config.yml)
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: r+ga1oEoQH/XSWzeVsf3wYa0mNJCLZNWMRSOz0+KSVADPh9CPqna/MconPeHsreMfBCtA/26B6DjUBzAgYbHJ6T+cKKnuI9j9er8j9Pd3VPFKMsG0Zvaeiwi2oR32bh9PS5+JMegMS2p/wScRNlICIfAcWpqDE428ctyMyAh3gCTiDvCBbPYPJ0QhEOPdYQViY7aCrdoFBcAj5N7RgYJE98LW5oeqhtyMHvsv2uIt0mnyHqk0tNTH0Qt/wdNn55TMdUczblXoVyl+ctq3lpICcmuBg1Zf8tvurw/1auUHxA69PkZeA1ZPs9B68e645rWjU7esmQrsfXdFsiE2KVSw9FNCHWmRPr/IZcx8S9TTdooeQqdDrcOLJniKYmPKahFXFTN+NrFVs0m7TTxI9frNH58oZ3B1DKttAOUZTNHrJpF4aWTpJcDi5vRpqKGWb84JtJD8TpaI9KUASlpLrVHd5urYEi5Pe43XfIkIHi9reJa95xsiDzP0wiMxo6l0cb2Gzg9nvd3uuZK8AVHn5AMy0XsVL7jlyqFcgDAZY/SgMxw5uKydoBmrdlPYZp8R+5EyNkwNLZLDqSNNVpbo7YQL3Qt2yuRuP40M8XWETad6n7Suls3gFFLa9flsTG34tg6k5w7lBvLfXL3CQaDKlTb6+/4KoyN+sraLLKVPd9NA9g=
    on_success: always
